<?php
return [
    /*
      |--------------------------------------------------------------------------
      | Incite Web Application Constant
      |--------------------------------------------------------------------------
      |
     */
      'messages' => [
            'success'       => 'success',
            'status_changed_success' =>'Status changed successfully.',
            'required_field_missing'    => 'Mandatory field missing',
            'there_is_an_error' => 'There is an error.',
            'record_found' => 'Record found',
            'record_not_found' => 'Record not found',
            'record_inserted' => 'Record inserted',
            'record_deleted' => 'Record deleted',
            'record_updated' => "Record Updated.",
            'invalid_request' => 'Invalid request method.',
            'something_went_wrong' => 'Something Went Wrong Try Again Later.',
            'unauthorized' => 'Unauthorized Access.',
            'token_expired' => 'Token Epired',
            'mobile_exist' => 'Mobile no already exist',
            'email_exist' => 'Email id already exist',
            'email_invalid' => 'Invalid email',
            'blog_list' =>'List of all blog',
            'setting_list' =>'List of all settings',
            'bookmarked_success' =>'Successfully Bookmarked',
            'bookmark_removed' =>'Bookmark removed',
            'already_viewed' =>'Already viewed',
            'successfully_viewed' =>'Successfully viewed',
            'successfully_voted' => 'Successfully voted for the blog',
            'category_list' =>'List of all category',
            'registerd_successfully' =>'Registerd Successfully',
            'user_not_found' =>'User Not found',
            'use_valid_email_password' =>'Please use valid email and password',
            'password_reset_success' =>'Password Successfully reset',
            'profile_updated_success' =>'Profile updated successfully',
            'profile_picture_updated_success' =>'Profile picture updated successfully',
            'device_updated_success' =>'Device updated successfully',
            'account_deleted_success' =>'Account deleted succefully',
            'credential_not_found' =>'Credentials not found',
            'use_admin_credentials' =>'Please use admin login credentials',
            'blog_deleted_success' =>'Blog deleted successfully.',
            'banner_image_deleted_success' =>'Banner image deleted successfully.',
            'slider_post_deleted_success' =>'Slider post deleted successfully.',
            'category_deleted_success' =>'Category deleted successfully.',
            'role_deleted_success' =>'Role deleted successfully.',
            'post_saved_success' =>'Post saved successfully.',
            'rss_feed_deleted_success' =>'RSS Feed deleted successfully.',
            'login_success' =>'Login successfully',
            'signup_success' =>'Signup successfully',
            'otp_sent_on_email' =>'OTP has been sent to your email id',
            'password_reset_success' =>'Password reset successfully',
            'demo_app_warning' =>'This is only demo app you can\'t change this section',
            'unable_change_try_again' =>'unable to change try again.',
            'sub_admin_deleted_success' =>'Sub admin deleted successfully.',
            'slug_exist' =>'Slug already exist',
            'notification_sent' =>'Notification Sent',
            'quote_deleted' =>'quote deleted',
            'blog_not_found' => 'Blog not found',
            'notification_not_sent' =>'Notification Not Sent for Personalization Category'
      ],
      'voice_accent' => ['ar','bn-BD','bn-IN','bs','ca','cs-CZ','cy','da-DK','de-DE','el-GR','en-AU','en-GB','en-IN','en-NG','en-US','es-ES','es-US','et-EE','fil-PH','fi-FI','fr-CA','fr-FR','gu-IN','hi-IN','hu-HU','id-ID','it-IT','ja-JP','jv-ID','km-KH','kn-IN','ko-KR','ku','la','ml-IN','mr-IN','nb-NO','ne-NP','nl-NL','pl-PL','pt-BR','pt-PT','ro-RO','ru-RU','si-LK','sk-SK','sq','sr','su-ID','sv-SE','sw','ta-IN','te-IN','th-TH','tr-TR','uk-UA','ur-PK','vi-VN','yue-HK','zh-CN','zh-TW'],

      // 'voice_accent' => ['yue-HK','ko-KR','en-AU','id-ID','ta-IN','ja-JP','pt-BR','it-IT','pt-PT','fi-FI','uk-UA','es-ES','ru-RU','en-NG','da-DK','sw','ur-PK','bs','gu-IN','vi-VN','ku','th-TH','hu-HU','la','pl-PL','en-US','ar','ca','en-GB','fr-FR','jv-ID','bn-IN','el-GR','zh-TW','sv-SE','et-EE','ne-NP','tr-TR','es-US','km-KH','hi-IN','cy','su-ID','si-LK','fr-CA','mr-IN','en-IN','sr','sq','cs-CZ','kn-IN','fil-PH','bn-BD','nb-NO','nl-NL','sk-SK','zh-CN','ro-RO','de-DE','ml-IN','te-IN'],
      //'voice_accent' => ['ko-KR', 'ru-RU', 'zh-TW', 'hu-HU', 'th-TH', 'nb-NO', 'da-DK', 'tr-TR', 'et-EE', 'bs', 'sw', 'pt-PT', 'vi-VN', 'en-US', 'sv-SE', 'su-ID', 'bn-BD', 'el-GR', 'hi-IN', 'fi-FI', 'km-KH', 'bn-IN', 'fr-FR', 'uk-UA', 'en-AU', 'nl-NL', 'fr-CA', 'sr', 'pt-BR', 'si-LK', 'de-DE', 'ku', 'cs-CZ', 'pl-PL', 'sk-SK', 'fil-PH', 'it-IT', 'ne-NP', 'hr', 'zh-CN', 'es-ES', 'cy', 'ja-JP', 'sq', 'yue-HK', 'en-IN', 'es-US', 'jv-ID', 'la', 'id-ID', 'ro-RO', 'ca', 'ta', 'en-GB'],

      'news_api_language' => [ 
            'en'=>'English',
            'ar'=>'Arabic',
            'de'=>'German',
            'es'=>'Spanish',
            'fr'=>'French',
            'he'=>'Hebrew',
            'it'=>'Italian',
            'nl'=>'Dutch',
            'no'=>'Norwegian',
            'pt'=>'Portuguese',
            'ru'=>'Russian',
            'se'=>'Northern Sami',
            'ud'=>'ud',
            'zh'=>'Chinese',
            'hi'=>'Hindi'
      ],

      'admin_prefix'=>'admin',

      'font_family' => [ 
            'Times New Roman',
            'serif',
            'Times',
            'Arial',
            'Helvetica',
            'sans-serif',
            'Lucida Console',
            'Courier New',
            'monospace',
            'cursive',
            'Brush Script MT',
      ],

      'speech_lang_code' => [
            'en'=>'en-us',
            'hi'=>'hi-in',
            'ar'=>'ar-eg',
            'bg'=>'bg-bg',
            'bg'=>'cs-cz',
            'nl'=>'nl-be',
            'fr'=>'fr-fr',
            'de'=>'de-de',
            'el'=>'el-gr',
            'es'=>'es-es',
      ],


      // 'speech_voice' => [
      //       'Oda'=>'Oda (Female)',
      //       'Salim'=>'Salim (Male)',
      //       'Dimo'=>'Dimo (Male)',
      //       'Rut'=>'Rut (Female)',
      //       'Luli'=>'Luli (Female)',
      //       'Shu'=>'Shu (Female)',
      //       'Chow'=>'Chow (Female)',
      //       'Wang'=>'Wang (Male)',
      //       'Jia'=>'Jia (Female)',
      //       'Xia'=>'Xia (Female)',
      //       'Chen'=>'Chen (Male)',
      //       'Akemi'=>'Akemi (Female)',
      //       'Lin'=>'Lin (Female)',
      //       'Lee'=>'Lee (Male)',
      //       'Nikola'=>'Nikola (Male)',
      //       'Josef'=>'Josef (Male)',
      //       'Freja'=>'Freja (Female)',
      //       'Daan'=>'Daan (Male)',
      //       'Lotte'=>'Lotte (Female)',
      //       'Bram'=>'Bram (Male)',
      //       'Zoe'=>'Zoe (Female)',
      //       'Isla'=>'Isla (Female)',
      //       'Evie'=>'Evie (Female)',
      //       'Jack'=>'Jack (Male)',
      //       'Rose'=>'Rose (Female)',
      //       'Clara'=>'Clara (Female)',
      //       'Emma'=>'Emma (Female)',
      //       'Mason'=>'Mason (Male)',
      //       'Alice'=>'Alice (Female)',
      //       'Nancy'=>'Nancy (Female)',
      //       'Lily'=>'Lily (Female)',
      //       'Harry'=>'Harry (Male)',
      //       'Eka'=>'Eka (Female)',
      //       'Jai'=>'Jai (Female)',
      //       'Ajit'=>'Ajit (Male)',
      //       'Oran'=>'Oran (Male)',
      //       'Linda'=>'Linda (Female)',
      //       'Amy'=>'Amy (Female)',
      //       'Mary'=>'Mary (Female)',
      //       'John'=>'John (Male)',
      //       'Mike'=>'Mike (Male)',
      //       'Aada'=>'Aada (Female)',
      //       'Emile'=>'Emile (Female)',
      //       'Olivia'=>'Olivia (Female)',
      //       'Logan'=>'Logan (Female)',
      //       'Felix'=>'Felix (Male)',
      //       'Bette'=>'Bette (Female)',
      //       'Iva'=>'Iva (Female)',
      //       'Zola'=>'Zola (Female)',
      //       'Axel'=>'Axel (Male)',
      //       'Theo'=>'Theo (Male)',
      //       'Lukas'=>'Lukas (Male)',
      //       'Hanna'=>'Hanna (Female)',
      //       'Lina'=>'Lina (Female)',
      //       'Jonas'=>'Jonas (Male)',
      //       'Tim'=>'Tim (Male)',
      //       'Neo'=>'Neo (Male)',
      //       'Rami'=>'Rami (Male)',
      //       'Puja'=>'Puja (Female)',
      //       'Kabir'=>'Kabir (Male)',
      //       'Mate'=>'Mate (Male)',
      //       'Intan'=>'Intan (Male)',
      //       'Bria'=>'Bria (Female)',
      //       'Mia'=>'Mia (Female)',
      //       'Pietro'=>'Pietro (Male)',
      //       'Hina'=>'Hina (Female)',
      //       'Airi'=>'Airi (Female)',
      //       'Fumi'=>'Fumi (Female)',
      //       'Akira'=>'Akira (Male)',
      //       'Nari'=>'Nari (Female)',
      //       'Aqil'=>'Aqil (Male)',
      //       'Marte'=>'Marte (Female)',
      //       'Erik'=>'Erik (Male)',
      //       'Julia'=>'Julia (Female)',
      //       'Jan'=>'Jan (Male)',
      //       'Marcia'=>'Marcia (Female)',
      //       'Ligia'=>'Ligia (Female)',
      //       'Yara'=>'Yara (Female)',
      //       'Dinis'=>'Dinis (Male)',
      //       'Leonor'=>'Leonor (Female)',
      //       'Doru'=>'Doru (Male)',
      //       'Olga'=>'Olga (Female)',
      //       'Marina'=>'Marina (Female)',
      //       'Peter'=>'Peter (Male)',
      //       'Beda'=>'Beda (Male)',
      //       'Vid'=>'Vid (Male)',
      //       'Juana'=>'Juana (Female)',
      //       'Silvia'=>'Silvia (Female)',
      //       'Teresa'=>'Teresa (Female)',
      //       'Jose'=>'Jose (Male)',
      //       'Camila'=>'Camila (Female)',
      //       'Sofia'=>'Sofia (Female)',
      //       'Luna'=>'Luna (Female)',
      //       'Diego'=>'Diego (Male)',
      //       'Molly'=>'Molly (Female)',
      //       'Hugo'=>'Hugo (Male)',
      //       'Sai'=>'Sai (Male)',
      //       'Ukrit'=>'Ukrit (Male)',
      //       'Omer'=>'Omer (Male)',
      //       'Chi'=>'Chi (Male)',
      // ],

      'speech_voice' => [ 
            'Aada'=>'Aada (Female)', 
            'Airi'=>'Airi (Female)', 
            'Ajit'=>'Ajit (Male)', 
            'Akira'=>'Akira (Male)', 
            'Akemi'=>'Akemi (Female)',
            'Alice'=>'Alice (Female)',
            'Amy'=>'Amy (Female)',
            'Aqil'=>'Aqil (Male)',
            'Axel'=>'Axel (Male)',
            'Beda'=>'Beda (Male)',
            'Bette'=>'Bette (Female)',
            'Bram'=>'Bram (Male)',
            'Bria'=>'Bria (Female)',
            'Camila'=>'Camila (Female)',
            'Chen'=>'Chen (Male)',
            'Chi'=>'Chi (Male)',
            'Chow'=>'Chow (Female)',
            'Clara'=>'Clara (Female)',
            'Daan'=>'Daan (Male)',
            'Diego'=>'Diego (Male)',
            'Dimo'=>'Dimo (Male)',
            'Dinis'=>'Dinis (Male)',
            'Doru'=>'Doru (Male)',
            'Eka'=>'Eka (Female)',
            'Emile'=>'Emile (Female)',
            'Emma'=>'Emma (Female)',
            'Erik'=>'Erik (Male)',
            'Evie'=>'Evie (Female)',
            'Felix'=>'Felix (Male)',
            'Freja'=>'Freja (Female)',
            'Fumi'=>'Fumi (Female)',
            'Hanna'=>'Hanna (Female)',
            'Harry'=>'Harry (Male)',
            'Hina'=>'Hina (Female)',
            'Hugo'=>'Hugo (Male)',
            'Intan'=>'Intan (Male)',
            'Isla'=>'Isla (Female)',
            'Iva'=>'Iva (Female)',
            'Jack'=>'Jack (Male)',
            'Jai'=>'Jai (Female)',
            'Jan'=>'Jan (Male)',
            'Jia'=>'Jia (Female)',
            'John'=>'John (Male)',
            'Jonas'=>'Jonas (Male)',
            'Jose'=>'Jose (Male)',
            'Josef'=>'Josef (Male)',
            'Juana'=>'Juana (Female)',
            'Julia'=>'Julia (Female)', 
            'Kabir'=>'Kabir (Male)',
            'Lee'=>'Lee (Male)',
            'Leonor'=>'Leonor (Female)',  
            'Ligia'=>'Ligia (Female)',
            'Lily'=>'Lily (Female)',
            'Lin'=>'Lin (Female)',
            'Lina'=>'Lina (Female)',
            'Linda'=>'Linda (Female)',
            'Logan'=>'Logan (Female)',
            'Lotte'=>'Lotte (Female)',
            'Lukas'=>'Lukas (Male)',
            'Luli'=>'Luli (Female)',
            'Luna'=>'Luna (Female)',
            'Marcia'=>'Marcia (Female)',     
            'Marina'=>'Marina (Female)',
            'Marte'=>'Marte (Female)',
            'Mary'=>'Mary (Female)',   
            'Mason'=>'Mason (Male)',
            'Mate'=>'Mate (Male)',
            'Mia'=>'Mia (Female)',
            'Mike'=>'Mike (Male)',
            'Molly'=>'Molly (Female)',
            'Nari'=>'Nari (Female)',
            'Nancy'=>'Nancy (Female)',
            'Neo'=>'Neo (Male)', 
            'Nikola'=>'Nikola (Male)',
            'Oda'=>'Oda (Female)',
            'Olga'=>'Olga (Female)',
            'Olivia'=>'Olivia (Female)',
            'Omer'=>'Omer (Male)',
            'Oran'=>'Oran (Male)',
            'Peter'=>'Peter (Male)',
            'Pietro'=>'Pietro (Male)',
            'Puja'=>'Puja (Female)',
            'Rami'=>'Rami (Male)',
            'Rose'=>'Rose (Female)',
            'Rut'=>'Rut (Female)',
            'Sai'=>'Sai (Male)',
            'Salim'=>'Salim (Male)',
            'Shu'=>'Shu (Female)',
            'Silvia'=>'Silvia (Female)',
            'Sofia'=>'Sofia (Female)', 
            'Teresa'=>'Teresa (Female)',
            'Theo'=>'Theo (Male)',
            'Tim'=>'Tim (Male)',
            'Ukrit'=>'Ukrit (Male)',
            'Vid'=>'Vid (Male)', 
            'Wang'=>'Wang (Male)',
            'Xia'=>'Xia (Female)',
            'Yara'=>'Yara (Female)', 
            'Zoe'=>'Zoe (Female)', 
            'Zola'=>'Zola (Female)',  
      ], 
      
      // Blog TTS: curated Voice ↔ Accent mapping (used by blog create/edit screens)
      // Table: Voice, Accent (Locale Code), Language, Gender
      'blog_tts_voice_profiles' => [
            ['voice' => 'Linda', 'accent' => 'uk-UA', 'language' => 'Ukrainian (Ukraine)', 'gender' => 'Female'],
            ['voice' => 'Daniel', 'accent' => 'en-GB', 'language' => 'English (United Kingdom)', 'gender' => 'Male'],
            ['voice' => 'Samantha', 'accent' => 'en-US', 'language' => 'English (United States)', 'gender' => 'Female'],
            ['voice' => 'Karen', 'accent' => 'en-AU', 'language' => 'English (Australia)', 'gender' => 'Female'],
            ['voice' => 'Veena', 'accent' => 'en-IN', 'language' => 'English (India)', 'gender' => 'Female'],
            ['voice' => 'Thomas', 'accent' => 'fr-FR', 'language' => 'French (France)', 'gender' => 'Male'],
            ['voice' => 'Helena', 'accent' => 'es-ES', 'language' => 'Spanish (Spain)', 'gender' => 'Female'],
            ['voice' => 'Anna', 'accent' => 'de-DE', 'language' => 'German (Germany)', 'gender' => 'Female'],
            ['voice' => 'Yuki', 'accent' => 'ja-JP', 'language' => 'Japanese (Japan)', 'gender' => 'Female'],
            ['voice' => 'Carlos', 'accent' => 'pt-BR', 'language' => 'Portuguese (Brazil)', 'gender' => 'Male'],
      ],
      'blog_speech_accent_options' => [
            'uk-UA' => 'uk-UA — Ukrainian (Ukraine)',
            'en-GB' => 'en-GB — English (United Kingdom)',
            'en-US' => 'en-US — English (United States)',
            'en-AU' => 'en-AU — English (Australia)',
            'en-IN' => 'en-IN — English (India)',
            'fr-FR' => 'fr-FR — French (France)',
            'es-ES' => 'es-ES — Spanish (Spain)',
            'de-DE' => 'de-DE — German (Germany)',
            'ja-JP' => 'ja-JP — Japanese (Japan)',
            'pt-BR' => 'pt-BR — Portuguese (Brazil)',
      ],
      'blog_speech_voice' => [
            'Linda' => 'Linda (Female) — Ukrainian (Ukraine) [uk-UA]',
            'Daniel' => 'Daniel (Male) — English (United Kingdom) [en-GB]',
            'Samantha' => 'Samantha (Female) — English (United States) [en-US]',
            'Karen' => 'Karen (Female) — English (Australia) [en-AU]',
            'Veena' => 'Veena (Female) — English (India) [en-IN]',
            'Thomas' => 'Thomas (Male) — French (France) [fr-FR]',
            'Helena' => 'Helena (Female) — Spanish (Spain) [es-ES]',
            'Anna' => 'Anna (Female) — German (Germany) [de-DE]',
            'Yuki' => 'Yuki (Female) — Japanese (Japan) [ja-JP]',
            'Carlos' => 'Carlos (Male) — Portuguese (Brazil) [pt-BR]',
      ],
      'blog_speech_voice_by_accent' => [
            'uk-UA' => ['Linda'],
            'en-GB' => ['Daniel'],
            'en-US' => ['Samantha'],
            'en-AU' => ['Karen'],
            'en-IN' => ['Veena'],
            'fr-FR' => ['Thomas'],
            'es-ES' => ['Helena'],
            'de-DE' => ['Anna'],
            'ja-JP' => ['Yuki'],
            'pt-BR' => ['Carlos'],
      ],
      'blog_speech_accent_by_voice' => [
            'Linda' => 'uk-UA',
            'Daniel' => 'en-GB',
            'Samantha' => 'en-US',
            'Karen' => 'en-AU',
            'Veena' => 'en-IN',
            'Thomas' => 'fr-FR',
            'Helena' => 'es-ES',
            'Anna' => 'de-DE',
            'Yuki' => 'ja-JP',
            'Carlos' => 'pt-BR',
      ],
 
      'speech_voice_by_accent' => [
            'ar' => ['Aqil', 'Omer', 'Rami', 'Salim'],
            'bn-BD' => ['Ajit', 'Jai', 'Kabir', 'Puja', 'Sai'],
            'bn-IN' => ['Ajit', 'Jai', 'Kabir', 'Puja', 'Sai'],
            'bs' => ['Beda', 'Vid'],
            'ca' => ['Rut'],
            'cs-CZ' => ['Iva', 'Nikola'],
            'cy' => ['Alice', 'Harry', 'Lily', 'Nancy'],
            'da-DK' => ['Freja'],
            'de-DE' => ['Hanna', 'Jonas'],
            'el-GR' => ['Neo'],
            'en-AU' => ['Isla', 'Jack', 'Logan', 'Olivia'],
            'en-GB' => ['Alice', 'Harry', 'Lily', 'Nancy'],
            'en-IN' => ['Ajit', 'Jai', 'Kabir', 'Puja', 'Sai'],
            'en-NG' => ['Amy', 'John', 'Linda', 'Mary', 'Mike'],
            'en-US' => ['Amy', 'John', 'Linda', 'Mary', 'Mike'],
            'es-ES' => ['Camila', 'Diego', 'Jose', 'Juana', 'Luna', 'Silvia', 'Sofia', 'Teresa'],
            'es-US' => ['Camila', 'Diego', 'Jose', 'Juana', 'Luna', 'Silvia', 'Sofia', 'Teresa'],
            'et-EE' => ['Emile'],
            'fil-PH' => ['Amy', 'John', 'Linda', 'Mary', 'Mike'],
            'fi-FI' => ['Aada', 'Airi'],
            'fr-CA' => ['Bette', 'Clara'],
            'fr-FR' => ['Bette', 'Clara'],
            'gu-IN' => ['Ajit', 'Jai', 'Kabir', 'Puja', 'Sai'],
            'hi-IN' => ['Ajit', 'Jai', 'Kabir', 'Puja', 'Sai'],
            'hu-HU' => ['Marcia', 'Mate'],
            'id-ID' => ['Eka', 'Intan'],
            'it-IT' => ['Pietro'],
            'ja-JP' => ['Akemi', 'Akira', 'Fumi', 'Hina'],
            'jv-ID' => ['Eka', 'Intan'],
            'km-KH' => [],
            'kn-IN' => ['Ajit', 'Jai', 'Kabir', 'Puja', 'Sai'],
            'ko-KR' => ['Nari'],
            'ku' => [],
            'la' => ['Felix'],
            'ml-IN' => ['Ajit', 'Jai', 'Kabir', 'Puja', 'Sai'],
            'mr-IN' => ['Ajit', 'Jai', 'Kabir', 'Puja', 'Sai'],
            'nb-NO' => ['Oda'],
            'ne-NP' => ['Ajit', 'Jai', 'Kabir', 'Puja', 'Sai'],
            'nl-NL' => ['Bram', 'Daan', 'Lotte'],
            'pl-PL' => ['Jan', 'Julia'],
            'pt-BR' => ['Camila', 'Yara'],
            'pt-PT' => ['Dinis', 'Leonor', 'Ligia'],
            'ro-RO' => ['Doru'],
            'ru-RU' => ['Olga'],
            'si-LK' => ['Ajit', 'Jai', 'Kabir', 'Puja', 'Sai'],
            'sk-SK' => ['Iva', 'Nikola'],
            'sq' => [],
            'sr' => ['Beda', 'Vid'],
            'su-ID' => ['Eka', 'Intan'],
            'sv-SE' => ['Emma', 'Erik'],
            'sw' => [],
            'ta-IN' => ['Ajit', 'Jai', 'Kabir', 'Puja', 'Sai'],
            'te-IN' => ['Ajit', 'Jai', 'Kabir', 'Puja', 'Sai'],
            'th-TH' => ['Ukrit'],
            'tr-TR' => ['Oran'],
            'uk-UA' => ['Olga', 'Vid'],
            'ur-PK' => ['Aqil', 'Omer', 'Rami', 'Salim'],
            'vi-VN' => ['Chi'],
            'yue-HK' => ['Chow'],
            'zh-CN' => ['Chen', 'Jia', 'Wang', 'Xia'],
            'zh-TW' => ['Lee', 'Lin', 'Shu'],
      ],
 
      'paginate' => [ 
            'num_per_page' => 25, 
      ], 
];
